# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server import server_pb2 as grpc__server_dot_server__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_server/server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllItems = channel.unary_unary(
                '/ItemService/GetAllItems',
                request_serializer=grpc__server_dot_server__pb2.EmptyRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.Items.FromString,
                _registered_method=True)
        self.GetMultipleItems = channel.unary_unary(
                '/ItemService/GetMultipleItems',
                request_serializer=grpc__server_dot_server__pb2.MulItemsRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.Items.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/ItemService/CreateItem',
                request_serializer=grpc__server_dot_server__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.sucessResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/ItemService/UpdateItem',
                request_serializer=grpc__server_dot_server__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.sucessResponse.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/ItemService/DeleteItem',
                request_serializer=grpc__server_dot_server__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.sucessResponse.FromString,
                _registered_method=True)
        self.GetItemById = channel.unary_unary(
                '/ItemService/GetItemById',
                request_serializer=grpc__server_dot_server__pb2.GetItemByIdRequest.SerializeToString,
                response_deserializer=grpc__server_dot_server__pb2.Item.FromString,
                _registered_method=True)


class ItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMultipleItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=grpc__server_dot_server__pb2.EmptyRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.Items.SerializeToString,
            ),
            'GetMultipleItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultipleItems,
                    request_deserializer=grpc__server_dot_server__pb2.MulItemsRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.Items.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=grpc__server_dot_server__pb2.CreateItemRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.sucessResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=grpc__server_dot_server__pb2.UpdateItemRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.sucessResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=grpc__server_dot_server__pb2.DeleteItemRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.sucessResponse.SerializeToString,
            ),
            'GetItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemById,
                    request_deserializer=grpc__server_dot_server__pb2.GetItemByIdRequest.FromString,
                    response_serializer=grpc__server_dot_server__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ItemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/GetAllItems',
            grpc__server_dot_server__pb2.EmptyRequest.SerializeToString,
            grpc__server_dot_server__pb2.Items.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMultipleItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/GetMultipleItems',
            grpc__server_dot_server__pb2.MulItemsRequest.SerializeToString,
            grpc__server_dot_server__pb2.Items.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/CreateItem',
            grpc__server_dot_server__pb2.CreateItemRequest.SerializeToString,
            grpc__server_dot_server__pb2.sucessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/UpdateItem',
            grpc__server_dot_server__pb2.UpdateItemRequest.SerializeToString,
            grpc__server_dot_server__pb2.sucessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/DeleteItem',
            grpc__server_dot_server__pb2.DeleteItemRequest.SerializeToString,
            grpc__server_dot_server__pb2.sucessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/GetItemById',
            grpc__server_dot_server__pb2.GetItemByIdRequest.SerializeToString,
            grpc__server_dot_server__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
