# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/services/grpc/a.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backend/services/grpc/a.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62\x61\x63kend/services/grpc/a.proto\"\'\n\x14GenerateTokenRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x06Tokens\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\x12ValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\xa4\x01\n\x0b\x41uthService\x12\x1f\n\x05Login\x12\r.LoginRequest\x1a\x07.Tokens\x12%\n\x08Register\x12\x10.RegisterRequest\x1a\x07.Tokens\x12,\n\rValidateToken\x12\x06.Token\x1a\x13.ValidationResponse\x12\x1f\n\x0cRefreshToken\x12\x06.Token\x1a\x07.Tokensb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.services.grpc.a_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATETOKENREQUEST']._serialized_start=33
  _globals['_GENERATETOKENREQUEST']._serialized_end=72
  _globals['_TOKENS']._serialized_start=74
  _globals['_TOKENS']._serialized_end=125
  _globals['_LOGINREQUEST']._serialized_start=127
  _globals['_LOGINREQUEST']._serialized_end=174
  _globals['_REGISTERREQUEST']._serialized_start=176
  _globals['_REGISTERREQUEST']._serialized_end=240
  _globals['_TOKEN']._serialized_start=242
  _globals['_TOKEN']._serialized_end=264
  _globals['_VALIDATIONRESPONSE']._serialized_start=266
  _globals['_VALIDATIONRESPONSE']._serialized_end=304
  _globals['_AUTHSERVICE']._serialized_start=307
  _globals['_AUTHSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
